FROM python:3.11.4 as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --with dev --output requirements.txt --without-hashes


FROM python:3.11.4

WORKDIR /api

ENV PYTHONPATH="/api"

COPY --from=requirements-stage /tmp/requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY . .


CMD ["python", "/api/api_konsi/infrastructure/server.py"]